from src.core.config.settings_base import BaseSettings


class TischREMSettings(BaseSettings):
    """
    Configuration for the Phenom XL TischREM device.
    Overrides device-specific settings from BaseSettings.
    """

    # ──────────────────────────────────────────────────────────────────────────────
    # 📂 File Settings
    # ──────────────────────────────────────────────────────────────────────────────
    DEBOUNCE_TIME = 2 # seconds
    ALLOWED_EXTENSIONS = {
        ".tiff", ".tif", ".TIFF", ".TIF",
    }

    # ──────────────────────────────────────────────────────────────────────────────
    # 📟 Device Identity
    # ──────────────────────────────────────────────────────────────────────────────
    DEVICE_TYPE = "REM"
    DEVICE_USER_KADI_ID = "test-rem-01-usr"
    DEVICE_USER_PERSISTENT_ID = 14
    DEVICE_RECORD_PERSISTENT_ID = 172

    # ──────────────────────────────────────────────────────────────────────────────
    # 📝 Metadata Defaults
    # ──────────────────────────────────────────────────────────────────────────────
    RECORD_TAGS = [
        "Electron Microscopy",
    ]

    DEFAULT_RECORD_DESCRIPTION = r"""
    # Default Description
    *Can be edited and/or overwritten*  
    **Please provide a detailed description of the data contained in this record, especially if the data will be used in publications or future research.**

    ---

    ## Overview

    **Device:**  
    Data in this record was generated by a **Phenom XL TischREM**, manufactured by Thermo Fisher.

    ## Data Types

    1. **TIFF Images**  
       - The device primarily generates high-resolution TIFF images.  
       - Each image includes metadata describing measurement parameters (e.g., voltage, pixel dimension).

    2. **Elemental Analysis**  
       - Analyses can be performed at a point, along a line, or within a defined region.  
       - Results typically include:  
         - **Documentation Files** – Summaries of measurement settings.  
         - **Images** – Overlaid with elemental signals or regions of interest.  
         - **Graphs** – Depicting elemental composition and distribution.

    3. **Surface Profiling**  
       - Although used infrequently, this feature produces:  
         - **Documentation Files** – Descriptions of the profiling methods.  
         - **Images** – Visual overviews of the sample’s surface.  
         - **Heat Maps** – Indicating surface elevations or contours.  
       - **Note:** Data integration of these file types is currently not supported. If you require this integration, please contact the system administrator.

    ---

    **Please ensure all relevant information (such as measurement conditions, parameters or additional metadata) is accurately recorded here for future reference and publication.**
    """
