"""Configuration builder for the dpost RHE KINEXUS device plugin."""

from __future__ import annotations

from dpost.application.config import (
    DeviceConfig,
    DeviceFileSelectors,
    DeviceMetadata,
    SessionSettings,
    WatcherSettings,
)


def build_config() -> DeviceConfig:
    """Return the Kinexus device configuration."""
    return DeviceConfig(
        identifier="rhe_kinexus",
        metadata=DeviceMetadata(
            user_kadi_id="rhe-01-usr",
            user_persistent_id=49,
            record_kadi_id="rhe_01",
            record_persistent_id=849,
            device_abbr="RHE",
            record_tags=("Rheology",),
            default_record_description=r"""
**Overview**\n\n"
This record contains data generated by a Kinexus Pro+ rotational rheometer. "
It typically includes:\n"
- Native project file archived as a .zip (bundled from .rdf)\n"
- Human-readable export(s) such as .csv\n\n"
**Data Types**\n\n"
Native (.rdf) is zipped for archival; exports (.csv) are appended to the record."
""",
        ),
        files=DeviceFileSelectors(
            native_extensions=frozenset({".rdf"}),
            exported_extensions=frozenset({".csv"}),
        ),
        session=SessionSettings(timeout_seconds=600),
        watcher=WatcherSettings(
            poll_seconds=1.0,
            max_wait_seconds=30,
            stable_cycles=2,
        ),
    )
