"""
sync_manager.py

This module defines the ISyncManager interface and its concrete implementation, SyncManager.
It handles synchronization operations between local records and a remote database using the
KadiManager. The SyncManager ensures that records are properly uploaded and maintained in
the database, including handling file uploads and updating record attributes.
"""

import os
from abc import ABC, abstractmethod

from src.records.local_record import LocalRecord
from src.storage.path_manager import PathManager
from src.app.logger import setup_logger
from src.config.settings import DEVICE_RECORD_ID, DEFAULT_REM_RECORD_DESCRIPTION

from kadi_apy import KadiManager

# Initialize the logger for this module
logger = setup_logger(__name__)


class ISyncManager(ABC):
    """
    Interface for managing synchronization operations between local records and the database.
    
    This abstract base class defines the essential methods that any synchronization manager
    implementation must provide. It ensures consistency and standardization across different
    synchronization processes within the application.
    """

    @abstractmethod
    def sync_record_to_database(self, local_record: LocalRecord):
        """
        Synchronize a local record to the database.

        Args:
            local_record (LocalRecord): The local record to synchronize.
        """
        pass


class SyncManager(ISyncManager):
    """
    Concrete implementation of ISyncManager that handles synchronization of local records
    to a remote database using KadiManager.

    The SyncManager class provides methods to upload records and their associated files to
    the database. It ensures that records are properly created or updated in the database,
    and that all relevant files are uploaded and marked as synchronized.
    """

    def __init__(self, db_manager):
        """
        Initializes the SyncManager with a database manager instance.

        Args:
            db_manager (callable): A factory or context manager that provides an instance
                                    of KadiManager for database operations.
        """
        self.db_manager_factory = db_manager

    def sync_record_to_database(self, local_record: LocalRecord):
        """
        Synchronizes a LocalRecord object to the remote database.

        This method performs the following actions:
            1. Connects to the database using the provided db_manager.
            2. Creates or retrieves a database record based on the local_record's long_id.
            3. If the record is not already in the database, sets its attributes and links it.
            4. Iterates through all associated files in the LocalRecord:
                - Uploads each file that hasn't been uploaded yet.
                - Marks the file as uploaded in the LocalRecord.
            5. Marks the LocalRecord as being in the database.

        Args:
            local_record (LocalRecord): The local record to synchronize.

        Raises:
            Exception: If any error occurs during the synchronization process.
        """
        try:
            # Establish a connection to the database using the db_manager_factory
            with self.db_manager_factory as db_manager:
                db_manager: KadiManager  # Type hint for clarity

                # Create a new record in the database or retrieve it if it already exists
                db_record = db_manager.record(create=True, identifier=local_record.long_id)
                logger.debug(f"Database record obtained for identifier '{local_record.long_id}'.")

                if not local_record.is_in_db:
                    # Set essential attributes for the new database record
                    db_record.set_attribute('title', local_record.name)
                    db_record.set_attribute('description', DEFAULT_REM_RECORD_DESCRIPTION)
                    db_record.set_attribute('type', 'rawdata')

                    # Add a relevant tag to the record for categorization
                    db_record.add_tag('Electron Microscopy')

                    # Link the record to the device record ID with a descriptive relationship
                    db_record.link_record(DEVICE_RECORD_ID, 'generated by')
                    logger.info(f"Initialized new database record '{local_record.long_id}' with attributes and tags.")

                # Iterate through all files associated with the local record
                for file_path, uploaded in local_record.files_uploaded.items():
                    if not uploaded:
                        # Upload the file to the database
                        db_record.upload_file(file_path)
                        # Mark the file as uploaded in the local record
                        local_record.files_uploaded[file_path] = True
                        logger.info(f"Uploaded file: {os.path.basename(file_path)}")

                # After uploading all files, mark the local record as being in the database
                local_record.is_in_db = True
                logger.info(f"All files for record '{local_record.long_id}' have been synced to the database.")
        
        except Exception as e:
            # Log any exceptions that occur during the synchronization process
            logger.exception(f"Failed to upload files to the database: {e}")
            raise e  # Re-raise the exception after logging

