import os
from abc import ABC, abstractmethod

from src.records.local_record import LocalRecord
from src.app.logger import setup_logger
from src.config.settings import DEFAULT_REM_RECORD_DESCRIPTION

from kadi_apy import KadiManager

logger = setup_logger(__name__)

class ISyncManager(ABC):
    """
    Interface for managing synchronization operations between local records and the database.
    """

    @abstractmethod
    def sync_record_to_database(self, local_record: LocalRecord):
        """
        Synchronize a local record to the database.

        :param local_record: The local record to synchronize.
        """
        pass


class SyncManager(ISyncManager):
    def __init__(self, db_manager):
        # db_manager_factory could be something like KadiManager or a callable that returns a DB manager instance.
        self.db_manager_factory = db_manager

    def sync_record_to_database(self, local_record: LocalRecord):
        try:
            with self.db_manager_factory as db_manager:
                db_manager: KadiManager
                db_record = db_manager.record(create=True, identifier=local_record.long_id)
                
                if not local_record.is_in_db:
                    db_record.set_attribute('title', local_record.name)
                    db_record.set_attribute('description', DEFAULT_REM_RECORD_DESCRIPTION)
                    db_record.add_tag('Electron Microscopy')
                    db_record.link_record(190, 'generated by')

                for file_path, uploaded in local_record.file_uploaded.items():
                    if not uploaded:
                        db_record.upload_file(file_path)
                        local_record.file_uploaded[file_path] = True
                        logger.info(f"Uploaded file: {os.path.basename(file_path)}")
                local_record.is_in_db = True
                logger.info("Files have been synced to the database.")
        except Exception as e:
            logger.exception(f"Failed to upload files to the database: {e}")
