"""Configuration factory for the NETZSCH/Malvern Kinexus Pro+ rheometer."""
from __future__ import annotations

from ipat_watchdog.core.config import (
    DeviceConfig,
    DeviceFileSelectors,
    DeviceMetadata,
    SessionSettings,
    WatcherSettings,
)

def build_config() -> DeviceConfig:
    """Return the Kinexus device configuration (mirrors Horiba style)."""
    return DeviceConfig(
        identifier="rhe_kinexus",
        metadata=DeviceMetadata(
            user_kadi_id="<tbd>",
            user_persistent_id="<tbd>",
            record_kadi_id="<tbd>",
            record_persistent_id="<tbd>",
            device_abbr="RHE",
            record_tags=("Rheology",),
            default_record_description=r"""
**Overview**\n\n"
This record contains data generated by a Kinexus Pro+ rotational rheometer. "
It typically includes:\n"
- Native project file archived as a .zip (bundled from .rdf)\n"
- Human-readable export(s) such as .csv\n\n"
**Data Types**\n\n"
Native (.rdf) is zipped for archival; exports (.csv) are appended to the record."
"""
            ),
        files=DeviceFileSelectors(
            native_extensions=frozenset({".rdf"}),   # Kinexus native project files
            exported_extensions=frozenset({".csv"}), # rSpace exports (extend to .txt/.pdf if needed)
        ),
        session=SessionSettings(
            timeout_seconds=600,  # adjust to typical run completion / copy times
        ),
        watcher=WatcherSettings(
            poll_seconds=1.0,
            max_wait_seconds=30,
            stable_cycles=2,
        ),
    )
