"""Configuration builder for the dpost SEM PHENOM XL2 device plugin."""

from __future__ import annotations

import re

from dpost.application.config import (
    DeviceConfig,
    DeviceFileSelectors,
    DeviceMetadata,
    SessionSettings,
    StabilityOverride,
    WatcherSettings,
)


def build_config() -> DeviceConfig:
    """Return the PHENOM XL2 SEM device configuration."""
    return DeviceConfig(
        identifier="sem_phenomxl2",
        metadata=DeviceMetadata(
            user_kadi_id="sem-01-usr",
            user_persistent_id=22,
            record_kadi_id="sem_01",
            record_persistent_id=190,
            device_abbr="SEM",
            record_tags=("Electron Microscopy",),
            default_record_description=r"""
    # Default Description
    *Can be edited and/or overwritten*  
    **Please provide a detailed description of the data contained in this record, especially if the data will be used in publications or future research.**

    ---

    ## Overview

    **Device:**  
    Data in this record was generated by a **Phenom XL TischREM**, manufactured by Thermo Fisher.

    ## Data Types

    1. **TIFF Images**  
       - The device primarily generates high-resolution TIFF images.  
       - Each image includes metadata describing measurement parameters (e.g., voltage, pixel dimension).

    2. **Elemental Analysis**  
       - Analyses can be performed at a point, along a line, or within a defined region.  
       - Results typically include:  
         - **Documentation Files** - Summaries of measurement settings.  
         - **Images** - Overlaid with elemental signals or regions of interest.  
         - **Graphs** - Depicting elemental composition and distribution.

    3. **Surface Profiling**  
       - Although used infrequently, this feature produces:  
         - **Documentation Files** - Descriptions of the profiling methods.  
         - **Images** - Visual overviews of the sample's surface.  
         - **Heat Maps** - Indicating surface elevations or contours.  
       - **Note:** Data integration of these file types is currently not supported. If you require this integration, please contact the system administrator.

    ---

    **Please ensure all relevant information (such as measurement conditions, parameters or additional metadata) is accurately recorded here for future reference and publication.**
    """,
        ),
        files=DeviceFileSelectors(
            native_extensions=frozenset({".tiff", ".tif", ".jpeg", ".jpg"}),
            allowed_folder_contents=frozenset({".odt", ".elid"}),
        ),
        session=SessionSettings(timeout_seconds=300),
        watcher=WatcherSettings(
            poll_seconds=1.5,
            max_wait_seconds=30,
            stable_cycles=3,
            temp_patterns=(".tmp", ".part", ".crdownload", ".~", "-journal"),
            temp_folder_regex=re.compile(r"_(old|new)\.[A-Za-z0-9]{6}$", re.IGNORECASE),
            sentinel_name=None,
            stability_overrides=(
                StabilityOverride(
                    suffixes=(".tiff", ".tif"),
                    poll_seconds=0.1,
                    stable_cycles=2,
                    max_wait_seconds=20,
                ),
                StabilityOverride(
                    suffixes=(".elid",),
                    poll_seconds=1.5,
                    stable_cycles=6,
                    max_wait_seconds=120,
                ),
            ),
        ),
    )
