# 02-build.ps1 — clean build (bundled .env only)

# --- Load env & cd to project root ---
. "$PSScriptRoot/00-env.ps1"
Set-Location -Path $env:PROJECT_ROOT

# --- SETTINGS / defaults ---
$CI_JOB_NAME   = if ($env:CI_JOB_NAME)   { $env:CI_JOB_NAME }   else { "horiba_blb" }
$CI_COMMIT_TAG = if ($env:CI_COMMIT_TAG) { $env:CI_COMMIT_TAG } elseif ($env:COMMIT_TAG) { $env:COMMIT_TAG } else { "vLocalTest" }
if (-not $env:BUILD_TIME) { $env:BUILD_TIME = (Get-Date -Format 'yyyy-MM-dd HH:mm:ss') + 'Z' }

$startTime = Get-Date

# --- Step 1: venv ---
if (!(Test-Path ".test_buildvenv")) {
  Write-Host "Creating build virtual environment..."
  python -m venv .test_buildvenv
}
. .\.test_buildvenv\Scripts\Activate.ps1
$python = ".\.test_buildvenv\Scripts\python.exe"

Write-Host "`nUpgrading pip/setuptools/wheel..."
& $python -m pip install --upgrade pip setuptools wheel

# --- Step 2: Install project with build extras/profile deps ---
# Handle empty PIP_EXTRAS gracefully
$extras = $env:PIP_EXTRAS
if ([string]::IsNullOrWhiteSpace($extras)) {
  $pipTarget = ".[build]"
} else {
  $pipTarget = ".[$extras,build]"
}
Write-Host "`nInstalling project with extras: $pipTarget"
& $python -m pip install -e $pipTarget
if ($LASTEXITCODE -ne 0) { Write-Error "pip install failed."; exit $LASTEXITCODE }

# --- Step 3: Create runtime artifacts to bundle (no external overrides) ---
Write-Host "`nCreating build/.env and build/version.txt..."
if (!(Test-Path "build")) { New-Item -ItemType Directory -Path "build" | Out-Null }

@"
# Generated by build script
PC_NAME=$CI_JOB_NAME
DEVICE_PLUGINS=$env:DEVICE_PLUGINS
"@ | Out-File -Encoding ascii build/.env -Force

@"
COMMIT_TAG=$CI_COMMIT_TAG
COMMIT_HASH=$env:COMMIT_HASH
GIT_BRANCH=$env:GIT_BRANCH
BUILD_TIME=$env:BUILD_TIME
"@ | Out-File -Encoding ascii build/version.txt -Force

# --- Step 4: Build executable from spec (spec handles hiddenimports) ---
$specFile = "build/specs/gen.spec"
if (!(Test-Path $specFile)) {
  Write-Error "Spec file not found: $specFile"
  exit 1
}

Write-Host "`nRunning PyInstaller using spec file: $specFile"

# Vars visible to the spec
$env:PC_NAME = $CI_JOB_NAME
if (-not $env:DEVICE_PLUGINS) { $env:DEVICE_PLUGINS = "" }

# Optional: make src/ importable during analysis (harmless if spec sets pathex)
$env:PYTHONPATH = "$(Get-Location)\src"

& $python -m PyInstaller $specFile --clean --noconfirm
if ($LASTEXITCODE -ne 0) { Write-Error "PyInstaller failed."; exit $LASTEXITCODE }

# --- Step 5: Verify output ---
$outputPath = "dist/wd-$CI_JOB_NAME.exe"
if (Test-Path $outputPath) {
  Write-Host "`nBuild succeeded. Executable: $outputPath"
} else {
  Write-Error "`nBuild failed. Expected output not found: $outputPath"
  exit 1
}

# --- Done ---
$duration = (Get-Date) - $startTime
Write-Host "`nBuild complete. Elapsed time: {0:hh\:mm\:ss}" -f $duration
