"""Configuration builder for the dpost PSA HORIBA device plugin."""

from __future__ import annotations

import re

from dpost.application.config import (
    DeviceConfig,
    DeviceFileSelectors,
    DeviceMetadata,
    SessionSettings,
    WatcherSettings,
)


def build_config() -> DeviceConfig:
    """Return the PSA Horiba device configuration."""
    return DeviceConfig(
        identifier="psa_horiba",
        metadata=DeviceMetadata(
            user_kadi_id="psa-01-usr",
            user_persistent_id=34,
            record_kadi_id="psa_01",
            record_persistent_id=613,
            device_abbr="PSA",
            record_tags=("Laser Diffraction",),
            default_record_description=r"""
    # Default Description
    *Can be edited and/or overwritten*
    **Please provide a detailed description of the data contained in this record, especially if the data will be used in publications or future research.**

    ---

    ## Overview

    **Device:**
    Data in this record was generated by a **Partica LA-960**, manufactured by Horiba.

    ## Data Types

    **Please ensure all relevant information (such as measurement conditions, parameters or additional metadata) is accurately recorded here for future reference and publication.**
    """,
        ),
        files=DeviceFileSelectors(
            native_extensions=frozenset({".ngb"}),
            exported_extensions=frozenset({".csv"}),
        ),
        session=SessionSettings(timeout_seconds=600),
        watcher=WatcherSettings(
            poll_seconds=0.25,
            max_wait_seconds=30,
            stable_cycles=2,
            temp_patterns=(".tmp", ".part", ".crdownload", ".~", "-journal"),
            temp_folder_regex=re.compile(r"\\.[A-Za-z0-9]{6}$"),
            sentinel_name=None,
        ),
    )
