"""Configuration factory for the Eirich Mixture."""
from __future__ import annotations

from ipat_watchdog.core.config import (
    DeviceConfig,
    DeviceFileSelectors,
    DeviceMetadata,
    SessionSettings,
    WatcherSettings,
)

_EIRICH_VARIANTS = {
    "EL1": {
        "device_abbr": "RMX_01",
        "identifier_suffix": "el1",
        "filename_patterns": ("Eirich_EL1_TrendFile_*",),
    },
    "R01": {
        "device_abbr": "RMX_02",
        "identifier_suffix": "r01",
        "filename_patterns": ("Eirich_R01_TrendFile_*",),
    },
}


def build_config(variant: str) -> DeviceConfig:
    """Return the Eirich device configuration for the requested variant."""
    key = variant.strip().upper()
    if key not in _EIRICH_VARIANTS:
        raise ValueError(f"Unknown Eirich variant '{variant}'")
    variant_info = _EIRICH_VARIANTS[key]
    identifier = f"rmx_eirich_{variant_info['identifier_suffix']}"
    return DeviceConfig(
        identifier=identifier,
        metadata=DeviceMetadata(
            user_kadi_id="<tbd>",
            user_persistent_id="<tbd>",
            record_kadi_id="<tbd>",
            record_persistent_id="<tbd>",
            device_abbr=variant_info["device_abbr"],
            record_tags=("Mixing",),
            default_record_description=r"""
**Overview**\n\n"
This record contains data generated by a Eirich mixture. "
It typically includes:\n"
- Human-readable export(s) such as .txt\n\n"
**Data Types**\n\n"
"""
            ),
        files=DeviceFileSelectors(
            exported_extensions=frozenset({".txt"}), # rSpace exports (extend to .txt/.pdf if needed)
            filename_patterns=variant_info["filename_patterns"],
        ),
        session=SessionSettings(
            timeout_seconds=600,  # adjust to typical run completion / copy times
        ),
        watcher=WatcherSettings(
            poll_seconds=1.0,
            max_wait_seconds=30,
            stable_cycles=2,
            sentinel_name=None,
            reappear_window_seconds=6.0,
        ),
    )
