"""Configuration factory for the Eirich Mixture."""
from __future__ import annotations

from ipat_watchdog.core.config import (
    DeviceConfig,
    DeviceFileSelectors,
    DeviceMetadata,
    SessionSettings,
    WatcherSettings,
)

def build_config() -> DeviceConfig:
    """Return the Eirich device configuration (mirrors Horiba style)."""
    return DeviceConfig(
        identifier="mix_eirich",
        metadata=DeviceMetadata(
            user_kadi_id="<tbd>",
            user_persistent_id="<tbd>",
            record_kadi_id="<tbd>",
            record_persistent_id="<tbd>",
            device_abbr="MIX",
            record_tags=("Mixing",),
            default_record_description=r"""
**Overview**\n\n"
This record contains data generated by a Eirich mixture. "
It typically includes:\n"
- Human-readable export(s) such as .txt\n\n"
**Data Types**\n\n"
"""
            ),
        files=DeviceFileSelectors(
            exported_extensions=frozenset({".txt"}), # rSpace exports (extend to .txt/.pdf if needed)
        ),
        session=SessionSettings(
            timeout_seconds=600,  # adjust to typical run completion / copy times
        ),
        watcher=WatcherSettings(
            poll_seconds=1.0,
            max_wait_seconds=30,
            stable_cycles=2,
            sentinel_name=None,
            reappear_window_seconds=6.0,
        ),
    )
