import os
import re

WATCH_DIR = os.path.abspath("Upload_Ordner")

DEST_DIR = os.path.abspath("Data")
RENAME_DIR = os.path.join(DEST_DIR, '00_To_Rename')
EXCEPTIONS_DIR = os.path.join(DEST_DIR, '01_Exceptions')
DAILY_RECORDS_JSON = os.path.join(DEST_DIR, 'record_persistence.json')  # phase out 

r"""
   ^(?!.*\.\.):   No consecutive dots ".." anywhere in the string
   (?!\.):        The first character must not be a dot
   [A-Za-z]+:     First segment = letters only
   -:             Literal underscore
   [A-Za-z]+:     Second segment = letters only
   -:             Another underscore
   [a-z0-9_ ]+:   Third segment = lower case letters, digits, underscores, and spaces
   (?<!\.):       Must not end with a dot
   $:             End of string

   Exemplary format: 'UserID-Institute-Sample_ID'
"""
FILENAME_PATTERN = re.compile(
   r'^(?!.*\.\.)(?!\.)([A-Za-z]+)-[A-Za-z]+-[A-Za-z0-9_ ]{1,30}+(?<!\.)$'
)

ID_SEP = '-'
FILE_SEP = '_'

LOG_FILE = os.path.join(DEST_DIR, 'rem_watchdog.log')

SESSION_TIMEOUT = 600 # 10 minutes

SYNC_LOGS = True
LOG_SYNC_INTERVAL = 60 # 1 minute

ALLOWED_EXTENSIONS = {
   ".tiff",
   ".tif",
   ".TIFF",
   ".TIF",
}

DEBOUNCE_TIME = 6

# TODO move rem related metainfo to rem space
DEVICE_ID = "test-rem-01-usr"
DEVICE_RECORD_ID = 172
DEVICE_USER_ID = 14
DEVICE_TYPE = "REM"
DEFAULT_REM_RECORD_DESCRIPTION = r"""
# Default Description
*Can be edited and/or overwritten*  
**Please provide a detailed description of the data contained in this record, especially if the data will be used in publications or future research.**

---

## Overview

**Device:**  
Data in this record was generated by a **Phenom XL TischREM**, manufactured by Thermo Fisher.

## Data Types

1. **TIFF Images**  
   - The device primarily generates high-resolution TIFF images.  
   - Each image includes metadata describing measurement parameters (e.g., voltage, pixel dimension).
---
2. **Elemental Analysis**  
   - Analyses can be performed at a point, along a line, or within a defined region.  
   - Results typically include:  
     - **Documentation Files** – Summaries of measurement settings.  
     - **Images** – Overlaid with elemental signals or regions of interest.  
     - **Graphs** – Depicting elemental composition and distribution.
---
3. **Surface Profiling**  
   - Although used infrequently, this feature produces:  
     - **Documentation Files** – Descriptions of the profiling methods.  
     - **Images** – Visual overviews of the sample’s surface.  
     - **Heat Maps** – Indicating surface elevations or contours.  
   - **Note:** Data integration of these file types is currently not supported. If you require this integration, please contact the system administrator.

---

**Please ensure all relevant information (such as measurement conditions, parameters or additional metadata) is accurately recorded here for future reference and publication.**
"""
