import os
import re

DEVICE_ID = "REM_01"
DEVICE_RECORD_ID = 190

WATCH_DIR = os.path.abspath("monitored_folder")
RENAME_DIR = os.path.join(WATCH_DIR, 'To_Rename')
RECORD_DIR = os.path.join(WATCH_DIR, 'Records')
EXCEPTIONS_DIR = os.path.join(WATCH_DIR, 'Exceptions')
ARCHIVED_FILES_JSON = os.path.join(RECORD_DIR, 'archive_db.json')
DAILY_RECORDS_JSON = os.path.join(RECORD_DIR, 'daily_records.json')

"""
   ^(?!.*\.\.): No consecutive dots ".." anywhere in the string
   (?!\.):       The first character must not be a dot
   [A-Za-z]+:    First segment = letters only
   _:            Literal underscore
   [A-Za-z]+:    Second segment = letters only
   _:            Another underscore
   [A-Za-z0-9._\- ]+: Third segment = letters, digits, underscore, dash, dot, space (characters to avoid: / \ : * ? " < > |)
   (?<!\.):      Must not end with a dot
   $:            End of string

   Exemplary format: 'Institute-UserID-Sample_ID'
"""
FILENAME_PATTERN = re.compile(
    r'^(?!.*\.\.)(?!\.)([A-Za-z]+)-[A-Za-z]+-[A-Za-z0-9._\-\ %]+(?<!\.)$'
)

ID_SEP = '-'
FILE_SEP = '_'

LOG_FILE = 'watchdog.log'

SESSION_TIMEOUT = 300 # 5 minutes

DEBOUNCE_TIME = 0.5

DEFAULT_REM_RECORD_DESCRIPTION = """
# Default Description
*Can be edited and/or overwritten*  
**Please provide a detailed description of the data contained in this record, especially if the data will be used in publications or future research.**

---

## Overview

**Device:**  
Data in this record was generated by a **Phenom XL TischREM**, manufactured by Thermo Fisher.

## Data Types

1. **TIFF Images**  
   - The device primarily generates high-resolution TIFF images.  
   - Each image includes metadata describing measurement parameters (e.g., voltage, pixel dimension).
---
2. **Elemental Analysis**  
   - Analyses can be performed at a point, along a line, or within a defined region.  
   - Results typically include:  
     - **Documentation Files** – Summaries of measurement settings.  
     - **Images** – Overlaid with elemental signals or regions of interest.  
     - **Graphs** – Depicting elemental composition and distribution.
---
3. **Surface Profiling**  
   - Although used infrequently, this feature produces:  
     - **Documentation Files** – Descriptions of the profiling methods.  
     - **Images** – Visual overviews of the sample’s surface.  
     - **Heat Maps** – Indicating surface elevations or contours.  
   - **Note:** Data integration of these file types is currently not supported. If you require this integration, please contact the system administrator.

---

**Please ensure all relevant information (such as measurement conditions or additional metadata) is accurately recorded here for future reference and publication.**
"""
