"""Processing domain contracts for V2."""

from dpost_v2.domain.processing.batch_models import (
    BatchCountConsistencyError,
    BatchMemberDuplicateError,
    BatchMetadataError,
    BatchOutcome,
    BatchStatus,
    build_batch_outcome,
)
from dpost_v2.domain.processing.models import (
    ProcessingOutcome,
    ProcessingOutcomeConsistencyError,
    ProcessingOutcomeMetadataError,
    ProcessingReason,
    ProcessingReasonNamespaceError,
    ProcessingStatus,
    ProcessingStatusError,
    failed_outcome,
    outcome_from_classification,
    outcome_from_dict,
    rejected_outcome,
    retry_outcome,
    success_outcome,
)
from dpost_v2.domain.processing.staging import (
    StagingAttemptOrderError,
    StagingEvent,
    StagingReasonRequiredError,
    StagingState,
    StagingStateUnknownError,
    StagingTransitionError,
    transition_state,
)
from dpost_v2.domain.processing.text import (
    NormalizedTextRecord,
    TextEncodingError,
    TextHeaderValidationError,
    TextNormalizationPolicy,
    TextParseOptions,
    TextParseStructureError,
    TextRowShapeError,
    normalize_token,
    parse_text_records,
)

__all__ = [
    "BatchCountConsistencyError",
    "BatchMemberDuplicateError",
    "BatchMetadataError",
    "BatchOutcome",
    "BatchStatus",
    "NormalizedTextRecord",
    "ProcessingOutcome",
    "ProcessingOutcomeConsistencyError",
    "ProcessingOutcomeMetadataError",
    "ProcessingReason",
    "ProcessingReasonNamespaceError",
    "ProcessingStatus",
    "ProcessingStatusError",
    "StagingAttemptOrderError",
    "StagingEvent",
    "StagingReasonRequiredError",
    "StagingState",
    "StagingStateUnknownError",
    "StagingTransitionError",
    "TextEncodingError",
    "TextHeaderValidationError",
    "TextNormalizationPolicy",
    "TextParseOptions",
    "TextParseStructureError",
    "TextRowShapeError",
    "build_batch_outcome",
    "failed_outcome",
    "normalize_token",
    "outcome_from_classification",
    "outcome_from_dict",
    "parse_text_records",
    "rejected_outcome",
    "retry_outcome",
    "success_outcome",
    "transition_state",
]
