. "$PSScriptRoot/00-env.ps1"
Set-Location -Path $env:PROJECT_ROOT

# Simulate GitLab "build" job locally in PowerShell

# --- SETTINGS / defaults ---
$CI_JOB_NAME   = if ($env:CI_JOB_NAME)   { $env:CI_JOB_NAME }   else { "zwick_blb" }
$CI_COMMIT_TAG = if ($env:CI_COMMIT_TAG) { $env:CI_COMMIT_TAG } elseif ($env:COMMIT_TAG) { $env:COMMIT_TAG } else { "vLocalTest" }
if (-not $env:BUILD_TIME) { $env:BUILD_TIME = (Get-Date -Format 'yyyy-MM-dd HH:mm:ss') + 'Z' }

# --- TIMER START ---
$startTime = Get-Date

# --- Step 1: Create Virtual Environment ---
if (!(Test-Path ".test_buildvenv")) {
    python -m venv .test_buildvenv
}

# --- Step 2: Activate Virtual Environment ---
. .\.test_buildvenv\Scripts\Activate.ps1
$python = ".\.test_buildvenv\Scripts\python.exe"

Write-Host "`nUpgrading pip/setuptools/wheel..."
& $python -m pip install --upgrade pip setuptools wheel

# --- Step 3: Install project with build extras/profile deps ---
$extras = $env:PIP_EXTRAS
if ([string]::IsNullOrWhiteSpace($extras)) {
    $pipTarget = ".[build]"
} else {
    $pipTarget = ".[$extras,build]"
}
Write-Host "`nInstalling project with extras: $pipTarget"
& $python -m pip install -e $pipTarget
if ($LASTEXITCODE -ne 0) { Write-Error "pip install failed."; exit $LASTEXITCODE }

# --- Step 4: Create runtime artifacts to bundle (no external overrides) ---
Write-Host "`nCreating build/.env and build/version-$CI_JOB_NAME.txt..."
if (!(Test-Path "build")) { New-Item -ItemType Directory -Path "build" | Out-Null }

@"
# Generated by build script
PC_NAME=$CI_JOB_NAME
DEVICE_PLUGINS=$env:DEVICE_PLUGINS
"@ | Out-File -Encoding ascii build/.env -Force

@"
COMMIT_TAG=$CI_COMMIT_TAG
COMMIT_HASH=$env:COMMIT_HASH
GIT_BRANCH=$env:GIT_BRANCH
BUILD_TIME=$env:BUILD_TIME
"@ | Out-File -Encoding ascii "build/version-$CI_JOB_NAME.txt" -Force

# --- Step 5: Build Executable ---
$specFile = "build/specs/gen.spec"
Write-Host "`nRunning PyInstaller using spec file: $specFile"
# Vars visible to the spec
$env:PC_NAME = $CI_JOB_NAME
if (-not $env:DEVICE_PLUGINS) { $env:DEVICE_PLUGINS = "" }
$env:PYTHONPATH = "$(Get-Location)\src"
pyinstaller $specFile --clean --noconfirm

# --- Step 7: Check Result ---
$outputPath = "dist/wd-$CI_JOB_NAME.exe"
if (Test-Path $outputPath) {
    Write-Host "`nBuild succeeded. Executable: $outputPath"
} else {
    Write-Error "`nBuild failed. Expected output not found: $outputPath"
    exit 1
}

# --- TIMER END ---
$endTime = Get-Date
$duration = $endTime - $startTime

Write-Host "`nBuild simulation complete."
Write-Host ("Elapsed time: {0:hh\:mm\:ss}" -f $duration)
