from ipat_watchdog.core.config.settings_base import BaseSettings
import re # TODO: configure import to base settings?

class HoribaLinksSettings(BaseSettings):
    """
    Configuration for the Horiba Partica LA-960 device.
    Overrides device-specific settings from BaseSettings.
    """

    SESSION_TIMEOUT = 600  # seconds

    POLL_SECONDS = 1.5
    MAX_WAIT_SECONDS = 30.0
    STABLE_CYCLES = 3
    TEMP_FOLDER_REGEX = re.compile(r"\.[A-Za-z0-9]{6}$")

    # ──────────────────────────────────────────────────────────────────────────────
    # 📂 File Settings
    # ──────────────────────────────────────────────────────────────────────────────
    ALLOWED_EXTENSIONS = {".txt", ".ngb"}
    ALLOWED_FOLDER_CONTENTS = {".txt", ".ngb"}

    # ──────────────────────────────────────────────────────────────────────────────
    # 📟 Device Identity
    # ──────────────────────────────────────────────────────────────────────────────
    
    DEVICE_USER_KADI_ID = "psa-01-usr"
    DEVICE_USER_PERSISTENT_ID = 34
    DEVICE_RECORD_KADI_ID = "psa_01"
    DEVICE_RECORD_PERSISTENT_ID = 613
    DEVICE_TYPE = "PSA"

    # ──────────────────────────────────────────────────────────────────────────────
    # 📝 Metadata Defaults
    # ──────────────────────────────────────────────────────────────────────────────
    RECORD_TAGS = [
        "Laser Diffraction",
    ]

    DEFAULT_RECORD_DESCRIPTION = r"""
    # Default Description
    *Can be edited and/or overwritten*  
    **Please provide a detailed description of the data contained in this record, especially if the data will be used in publications or future research.**

    ---

    ## Overview

    **Device:**  
    Data in this record was generated by a **Partica LA-960**, manufactured by Horiba.

    ## Data Types

    **Please ensure all relevant information (such as measurement conditions, parameters or additional metadata) is accurately recorded here for future reference and publication.**
    """
