"""Configuration factory for the Eirich mixer EL1."""

from __future__ import annotations

from ipat_watchdog.core.config import (
    DeviceConfig,
    DeviceFileSelectors,
    DeviceMetadata,
    SessionSettings,
    WatcherSettings,
)


def build_config() -> DeviceConfig:
    """Return the Eirich EL1 device configuration."""
    return DeviceConfig(
        identifier="rmx_eirich_el1",
        metadata=DeviceMetadata(
            user_kadi_id="rmx-01-usr",
            user_persistent_id=175,
            record_kadi_id="rmx_01",
            record_persistent_id=940,
            device_abbr="RMX_01",
            record_tags=("Mixing",),
            default_record_description=r"""
**Overview**\n\n"
This record contains data generated by a Eirich mixture. "
It typically includes:\n"
- Human-readable export(s) such as .txt\n\n"
**Data Types**\n\n"
""",
        ),
        files=DeviceFileSelectors(
            exported_extensions=frozenset(
                {".txt"}
            ),  # rSpace exports (extend to .txt/.pdf if needed)
            filename_patterns=("Eirich_EL1_TrendFile_*",),
        ),
        session=SessionSettings(
            timeout_seconds=600,  # adjust to typical run completion / copy times
        ),
        watcher=WatcherSettings(
            poll_seconds=1.0,
            max_wait_seconds=30,
            stable_cycles=2,
            sentinel_name=None,
            reappear_window_seconds=6.0,
        ),
    )
